Repository Kong/insomnia, pull requests merged in 2020-11, with the labels that each got.

#2794 Add support for gRPC request actions
  packages/insomnia-app/app/models/grpc-request-meta.js
  packages/insomnia-app/app/models/grpc-request.js
  packages/insomnia-app/app/models/helpers/__tests__/is-model.test.js
  packages/insomnia-app/app/models/helpers/is-model.js
  packages/insomnia-app/app/models/helpers/request-operations.js
  packages/insomnia-app/app/models/request-meta.js
  packages/insomnia-app/app/ui/components/dropdowns/request-actions-dropdown.js
  packages/insomnia-app/app/ui/components/modals/move-request-group-modal.js
  packages/insomnia-app/app/ui/components/modals/request-settings-modal.js
  packages/insomnia-app/app/ui/components/sidebar/sidebar-request-row.js
  packages/insomnia-app/app/ui/components/wrapper-debug.js
  packages/insomnia-app/app/ui/containers/app.js
  packages/insomnia-app/app/ui/redux/selectors.js
  packages/insomnia-app/app/ui/redux/sidebar-selectors.js
Labels: grpc

#2799 Extract foundational components from request and response panes
  packages/insomnia-app/app/ui/components/panes/blank-pane.js
  packages/insomnia-app/app/ui/components/panes/grpc-request-pane.js
  packages/insomnia-app/app/ui/components/panes/grpc-response-pane.js
  packages/insomnia-app/app/ui/components/panes/pane.js
  packages/insomnia-app/app/ui/components/panes/placeholder-request-pane.js
  packages/insomnia-app/app/ui/components/panes/placeholder-response-pane.js
  packages/insomnia-app/app/ui/components/panes/request-pane.js
  packages/insomnia-app/app/ui/components/panes/response-pane.js
  packages/insomnia-app/app/ui/components/wrapper-debug.js
Labels: grpc

#2798 Unsafe deletion of a protofile
  packages/insomnia-app/app/ui/components/modals/proto-files-modal.js
  packages/insomnia-app/app/ui/components/proto-file/proto-file-list-item.js
Labels: grpc

#2817 Introduce stub UI for gRPC request and response panes
  packages/insomnia-app/app/ui/components/dropdowns/grpc-method-dropdown.js
  packages/insomnia-app/app/ui/components/editors/grpc-editor.js
  packages/insomnia-app/app/ui/components/panes/grpc-request-pane.js
  packages/insomnia-app/app/ui/components/panes/grpc-response-pane.js
  packages/insomnia-app/app/ui/components/viewers/grpc-tabbed-messages.js
  packages/insomnia-app/app/ui/components/wrapper-debug.js
  packages/insomnia-app/app/ui/css/components/grpc-url-bar.less
  packages/insomnia-app/app/ui/css/components/tabs.less
  packages/insomnia-app/app/ui/css/constants/colors.less
  packages/insomnia-app/app/ui/css/index.less
Labels: UI/UX 🎨

#2795 Allow users to delete synced workspaces from the API
  packages/insomnia-app/app/sync/vcs/index.js
  packages/insomnia-app/app/ui/components/dropdowns/sync-dropdown.js
  packages/insomnia-app/app/ui/components/modals/sync-delete-modal.js
  packages/insomnia-app/app/ui/components/wrapper.js
Labels: sync/server

#2809 Support for gRPC Unary and Client streaming
  packages/insomnia-app/app/__mocks__/electron.js
  packages/insomnia-app/app/common/grpc-events.js
  packages/insomnia-app/app/main.development.js
  packages/insomnia-app/app/main/__tests__/ipc-grpc.test.js
  packages/insomnia-app/app/main/ipc-grpc.js
  packages/insomnia-app/app/models/__tests__/grpc-request.test.js
  packages/insomnia-app/app/models/grpc-request.js
  packages/insomnia-app/app/network/grpc/__fixtures__/hello.proto
  packages/insomnia-app/app/network/grpc/__mocks__/index.js
  packages/insomnia-app/app/network/grpc/__tests__/call-cache.test.js
  packages/insomnia-app/app/network/grpc/__tests__/method.test.js
  packages/insomnia-app/app/network/grpc/__tests__/proto-loader.test.js
  packages/insomnia-app/app/network/grpc/__tests__/response-callbacks.test.js
  packages/insomnia-app/app/network/grpc/call-cache.js
  packages/insomnia-app/app/network/grpc/index.js
  packages/insomnia-app/app/network/grpc/method.js
  packages/insomnia-app/app/network/grpc/proto-loader.js
  packages/insomnia-app/app/network/grpc/response-callbacks.js
  packages/insomnia-app/app/network/grpc/service-error.js
  packages/insomnia-app/app/network/grpc/write-proto-file.js
  packages/insomnia-app/app/ui/components/dropdowns/grpc-method-dropdown.js
  packages/insomnia-app/app/ui/components/editors/grpc-editor.js
  packages/insomnia-app/app/ui/components/panes/grpc-event-wrapper.js
  packages/insomnia-app/app/ui/components/panes/grpc-request-pane.js
  packages/insomnia-app/app/ui/components/panes/grpc-response-pane.js
  packages/insomnia-app/app/ui/components/viewers/grpc-tabbed-messages.js
  packages/insomnia-app/app/ui/components/wrapper-debug.js
  packages/insomnia-app/app/ui/containers/app.js
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
Labels: grpc

#2820 Add protofile modal design integration
  packages/insomnia-app/app/ui/components/base/file-input-button.js
  packages/insomnia-app/app/ui/components/modals/proto-files-modal.js
  packages/insomnia-app/app/ui/components/proto-file/proto-file-list-item.js
  packages/insomnia-app/app/ui/components/proto-file/proto-file-list.js
  packages/insomnia-components/components/list-group/list-group.js
  packages/insomnia-components/components/list-group/list-group.stories.js
Labels: UI/UX 🎨, grpc

#2813 gRPC state management
  packages/insomnia-app/app/__mocks__/electron.js
  packages/insomnia-app/app/common/grpc-events.js
  packages/insomnia-app/app/main.development.js
  packages/insomnia-app/app/main/__tests__/grpc-ipc-main.test.js
  packages/insomnia-app/app/main/grpc-ipc-main.js
  packages/insomnia-app/app/network/grpc/__tests__/response-callbacks.test.js
  packages/insomnia-app/app/network/grpc/call-cache.js
  packages/insomnia-app/app/network/grpc/index.js
  packages/insomnia-app/app/network/grpc/response-callbacks.js
  packages/insomnia-app/app/network/grpc/service-error.js
  packages/insomnia-app/app/ui/components/buttons/grpc-send-button.js
  packages/insomnia-app/app/ui/components/dropdowns/grpc-method-dropdown.js
  packages/insomnia-app/app/ui/components/grpc-spinner.js
  packages/insomnia-app/app/ui/components/panes/grpc-event-wrapper.js
  packages/insomnia-app/app/ui/components/panes/grpc-request-pane.js
  packages/insomnia-app/app/ui/components/panes/grpc-response-pane.js
  packages/insomnia-app/app/ui/components/sidebar/sidebar-request-row.js
  packages/insomnia-app/app/ui/components/tags/grpc-status-tag.js
  packages/insomnia-app/app/ui/components/viewers/grpc-tabbed-messages.js
  packages/insomnia-app/app/ui/containers/app.js
  packages/insomnia-app/app/ui/context/grpc/__schemas__/grpc-message-schema.js
  packages/insomnia-app/app/ui/context/grpc/__schemas__/grpc-status-object-schema.js
  packages/insomnia-app/app/ui/context/grpc/__schemas__/index.js
  packages/insomnia-app/app/ui/context/grpc/__schemas__/request-state-schema.js
  packages/insomnia-app/app/ui/context/grpc/__tests__/grpc-context.test.js
  packages/insomnia-app/app/ui/context/grpc/__tests__/grpc-ipc-renderer.test.js
  packages/insomnia-app/app/ui/context/grpc/__tests__/grpc-reducer.test.js
  packages/insomnia-app/app/ui/context/grpc/grpc-actions.js
  packages/insomnia-app/app/ui/context/grpc/grpc-context.js
  packages/insomnia-app/app/ui/context/grpc/grpc-ipc-renderer.js
  packages/insomnia-app/app/ui/context/grpc/grpc-reducer.js
  packages/insomnia-app/app/ui/context/grpc/index.js
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
Labels: grpc

#2827 Add TLS/SSL support
  packages/insomnia-app/app/network/grpc/__tests__/parse-grpc-url.test.js
  packages/insomnia-app/app/network/grpc/index.js
  packages/insomnia-app/app/network/grpc/parse-grpc-url.js
Labels: grpc

#2790 Fix version control beta merge conflicts where objects have been deleted
  packages/insomnia-app/app/ui/components/modals/sync-merge-modal.js
Labels: sync/server

#2824 Updating base font sizes to fix previous merged PR
  packages/insomnia-app/app/ui/css/constants/dimensions.less
Labels: Improvement 💄, UI/UX 🎨

#2828 Allow changing the protofile for a request
  packages/insomnia-app/app/models/__tests__/grpc-request.test.js
  packages/insomnia-app/app/models/grpc-request.js
  packages/insomnia-app/app/network/grpc/__mocks__/proto-loader.js
  packages/insomnia-app/app/network/grpc/index.js
  packages/insomnia-app/app/network/grpc/method.js
  packages/insomnia-app/app/network/grpc/proto-loader.js
  packages/insomnia-app/app/ui/components/buttons/grpc-send-button.js
  packages/insomnia-app/app/ui/components/dropdowns/grpc-method-dropdown.js
  packages/insomnia-app/app/ui/components/panes/grpc-request-pane.js
  packages/insomnia-app/app/ui/components/panes/grpc-request-pane/index.js
  packages/insomnia-app/app/ui/components/panes/grpc-request-pane/use-change-handlers.js
  packages/insomnia-app/app/ui/components/panes/grpc-request-pane/use-selected-method.js
  packages/insomnia-app/app/ui/context/grpc/__schemas__/grpc-method-definition-schema.js
  packages/insomnia-app/app/ui/context/grpc/__schemas__/index.js
  packages/insomnia-app/app/ui/context/grpc/__schemas__/request-state-schema.js
  packages/insomnia-app/app/ui/context/grpc/__tests__/grpc-reducer.test.js
  packages/insomnia-app/app/ui/context/grpc/grpc-actions.js
  packages/insomnia-app/app/ui/context/grpc/grpc-reducer.js
Labels: grpc

#2830 gRPC with Insomnia export format V4
  packages/insomnia-app/app/common/__tests__/import.test.js
  packages/insomnia-app/app/common/import.js
  packages/insomnia-app/app/models/helpers/__tests__/is-model.test.js
  packages/insomnia-app/app/models/helpers/is-model.js
  packages/insomnia-app/app/models/helpers/request-operations.js
  packages/insomnia-app/app/ui/components/export-requests/request-row.js
  packages/insomnia-app/app/ui/components/export-requests/tree.js
  packages/insomnia-app/app/ui/components/modals/export-requests-modal.js
  packages/insomnia-app/app/ui/redux/modules/global.js
Labels: grpc

#2832 Support reuploading a proto file
  packages/insomnia-app/app/common/grpc-events.js
  packages/insomnia-app/app/common/select-file-or-folder.js
  packages/insomnia-app/app/main/__tests__/grpc-ipc-main.test.js
  packages/insomnia-app/app/main/grpc-ipc-main.js
  packages/insomnia-app/app/models/grpc-request.js
  packages/insomnia-app/app/network/grpc/__mocks__/index.js
  packages/insomnia-app/app/network/grpc/index.js
  packages/insomnia-app/app/ui/components/base/file-input-button.js
  packages/insomnia-app/app/ui/components/modals/proto-files-modal.js
  packages/insomnia-app/app/ui/components/panes/grpc-request-pane/__tests__/use-proto-file-reload.test.js
  packages/insomnia-app/app/ui/components/panes/grpc-request-pane/index.js
  packages/insomnia-app/app/ui/components/panes/grpc-request-pane/use-change-handlers.js
  packages/insomnia-app/app/ui/components/panes/grpc-request-pane/use-proto-file-reload.js
  packages/insomnia-app/app/ui/components/panes/grpc-request-pane/use-selected-method.js
  packages/insomnia-app/app/ui/components/proto-file/proto-file-list-item.js
  packages/insomnia-app/app/ui/components/proto-file/proto-file-list.js
  packages/insomnia-app/app/ui/components/wrapper.js
  packages/insomnia-app/app/ui/containers/app.js
  packages/insomnia-app/app/ui/context/grpc/__mocks__/grpc-actions.js
  packages/insomnia-app/app/ui/context/grpc/__tests__/grpc-reducer.test.js
  packages/insomnia-app/app/ui/context/grpc/grpc-actions.js
  packages/insomnia-app/app/ui/context/grpc/grpc-context.js
  packages/insomnia-app/app/ui/context/grpc/grpc-ipc-renderer.js
  packages/insomnia-app/app/ui/context/grpc/grpc-reducer.js
  packages/insomnia-app/app/ui/context/grpc/index.js
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
Labels: grpc

#2814 Support for server and bidi streaming
  packages/insomnia-app/app/common/grpc-events.js
  packages/insomnia-app/app/main/__tests__/grpc-ipc-main.test.js
  packages/insomnia-app/app/main/grpc-ipc-main.js
  packages/insomnia-app/app/network/grpc/__mocks__/index.js
  packages/insomnia-app/app/network/grpc/index.js
  packages/insomnia-app/app/ui/components/buttons/grpc-send-button.js
  packages/insomnia-app/app/ui/context/grpc/grpc-reducer.js
Labels: grpc

#2844 Show scrollbar when horizontal tab list exceeds available width.
  packages/insomnia-app/app/ui/css/components/tabs.less
Labels: UI/UX 🎨, bug

#2712 Add resizing for Design Preview and Testing Results panes
  packages/insomnia-app/app/ui/components/page-layout.js
  packages/insomnia-app/app/ui/components/panes/pane.js
  packages/insomnia-app/app/ui/components/wrapper-debug.js
  packages/insomnia-app/app/ui/components/wrapper-design.js
  packages/insomnia-app/app/ui/components/wrapper-unit-test.js
  packages/insomnia-app/app/ui/css/components/pane.less
  packages/insomnia-app/app/ui/css/components/request-pane.less
  packages/insomnia-app/app/ui/css/components/response-pane.less
  packages/insomnia-app/app/ui/css/components/spec-editor.less
  packages/insomnia-app/app/ui/css/components/unit-tests.less
  packages/insomnia-app/app/ui/css/components/wrapper.less
Labels: hacktoberfest-accepted

#2732 Adds sorting to GQL Documentation Browser
  packages/insomnia-app/app/ui/components/graph-ql-explorer/graph-ql-explorer-type.js
Labels: hacktoberfest-accepted

#2797 Remove redundant help menu item
  packages/insomnia-app/app/main/window-utils.js
Labels: hacktoberfest-accepted

#2852 Remove hinting and hide copy/move buttons
  packages/insomnia-app/app/ui/components/modals/request-create-modal.js
  packages/insomnia-app/app/ui/components/modals/request-settings-modal.js
Labels: grpc

#2859 gRPC URL bar spacing in Designer
  packages/insomnia-app/app/ui/css/components/request-pane.less
Labels: UI/UX 🎨

#2846 Add GrpcRequest and ProtoFile as accepted models for git sync
  packages/insomnia-app/app/sync/git/__tests__/ne-db-plugin.test.js
  packages/insomnia-app/app/sync/git/__tests__/parse-git-path.test.js
  packages/insomnia-app/app/sync/git/ne-db-plugin.js
  packages/insomnia-app/app/sync/git/parse-git-path.js
  packages/insomnia-app/app/ui/components/modals/git-staging-modal.js
Labels: grpc

#2740 Fix Copy as CURL with Multipart
  packages/insomnia-app/app/common/__tests__/har.test.js
  packages/insomnia-app/app/common/har.js
Labels: hacktoberfest-accepted

#2773 Add specification linting for files
  packages/insomnia-inso/src/commands/__fixtures__/openapi-spec.yaml
  packages/insomnia-inso/src/commands/__tests__/lint-specification.test.js
  packages/insomnia-inso/src/commands/lint-specification.js
Labels: hacktoberfest-accepted

#2864 Validate protofile during upload
  packages/insomnia-app/app/network/grpc/proto-loader.js
  packages/insomnia-app/app/ui/components/modals/proto-files-modal.js
  packages/insomnia-app/app/ui/components/proto-file/proto-file-list-item.js
  packages/insomnia-components/components/button.stories.js
  packages/insomnia-components/components/button/async-button.js
  packages/insomnia-components/components/button/async-button.stories.js
  packages/insomnia-components/components/button/button.js
  packages/insomnia-components/components/button/button.stories.js
  packages/insomnia-components/components/button/index.js
  packages/insomnia-components/components/dropdown/dropdown.stories.js
  packages/insomnia-components/components/list-group/unit-test-item.js
  packages/insomnia-components/components/notice-table.js
  packages/insomnia-components/index.js
Labels: grpc

#2869 Fix re-uploading a protofile when it is not linked to a request
  packages/insomnia-app/app/__mocks__/electron.js
  packages/insomnia-app/app/ui/components/modals/proto-files-modal.js
  packages/insomnia-app/app/ui/context/grpc/__tests__/grpc-ipc-renderer.test.js
  packages/insomnia-app/app/ui/context/grpc/__tests__/grpc-reducer.test.js
  packages/insomnia-app/app/ui/context/grpc/grpc-actions.js
  packages/insomnia-app/app/ui/context/grpc/grpc-ipc-renderer.js
Labels: grpc

#2736 Allow prompt values to be clear + add actions to template tag plugin API
  packages/insomnia-app/app/plugins/context/index.js
  packages/insomnia-app/app/plugins/context/store.js
  packages/insomnia-app/app/templating/base-extension.js
  packages/insomnia-app/app/templating/extensions/index.js
  packages/insomnia-app/app/templating/index.js
  packages/insomnia-app/app/templating/utils.js
  packages/insomnia-app/app/ui/components/templating/tag-editor.js
  packages/insomnia-app/app/ui/css/components/forms.less
  plugins/insomnia-plugin-prompt/index.js
Labels: hacktoberfest-accepted
