Repository Kong/insomnia, pull requests merged in 2020-07, with the labels that each got.

#2305 Support toggling of auto beautify in editor.
  packages/insomnia-app/app/ui/components/codemirror/code-editor.js
  packages/insomnia-app/app/ui/components/dropdowns/prettify-dropdown.js
Labels: Accepted 👌, UI/UX 🎨

#2386 2377 paste issue fix
  packages/insomnia-app/app/ui/components/codemirror/one-line-editor.js
Labels: Bug

#2441 Editor search selection contrast
  packages/insomnia-app/app/ui/css/editor/general.less
Labels: Accessibility 🌍, UI/UX 🎨

#2465 Storybook categories & component organization
  packages/insomnia-components/components/breadcrumb.stories.js
  packages/insomnia-components/components/button.stories.js
  packages/insomnia-components/components/card.stories.js
  packages/insomnia-components/components/dropdown/dropdown.stories.js
  packages/insomnia-components/components/gravatar-img.stories.js
  packages/insomnia-components/components/header.stories.js
  packages/insomnia-components/components/multi-switch.stories.js
  packages/insomnia-components/components/notice-table.stories.js
  packages/insomnia-components/components/radio-button-group.stories.js
  packages/insomnia-components/components/sidebar/sidebar.stories.js
  packages/insomnia-components/components/svg-icon.stories.js
  packages/insomnia-components/components/switch.stories.js
  packages/insomnia-components/components/table.stories.js
  packages/insomnia-components/components/toggle-switch.stories.js
  packages/insomnia-components/components/tooltip.stories.js
Labels: UI/UX 🎨
