Repository Kong/insomnia, pull requests merged in 2020-08, with the labels that each got.

#2433 Sidebar code mirror interactions
  package-lock.json
  package.json
  packages/insomnia-app/app/ui/components/codemirror/code-editor.js
  packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar-item.js
  packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
  packages/insomnia-app/app/ui/components/wrapper-design.js
  packages/insomnia-app/app/ui/css/components/spec-editor.less
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
  packages/insomnia-components/components/sidebar/index.js
  packages/insomnia-components/components/sidebar/sidebar-headers.js
  packages/insomnia-components/components/sidebar/sidebar-info.js
  packages/insomnia-components/components/sidebar/sidebar-invalid-section.js
  packages/insomnia-components/components/sidebar/sidebar-parameters.js
  packages/insomnia-components/components/sidebar/sidebar-paths.js
  packages/insomnia-components/components/sidebar/sidebar-requests.js
  packages/insomnia-components/components/sidebar/sidebar-responses.js
  packages/insomnia-components/components/sidebar/sidebar-schemas.js
  packages/insomnia-components/components/sidebar/sidebar-security.js
  packages/insomnia-components/components/sidebar/sidebar-servers.js
  packages/insomnia-components/components/sidebar/sidebar.stories.js
Labels: UI/UX 🎨

#2484 Bring path validation into paths component. Error boundary around sidebar.
  packages/insomnia-app/app/ui/components/wrapper-design.js
  packages/insomnia-components/components/sidebar/index.js
  packages/insomnia-components/components/sidebar/sidebar-paths.js
Labels: Bug, UI/UX 🎨

#2489 Updating storybook styling
  packages/insomnia-components/.storybook/manager.js
  packages/insomnia-components/.storybook/preview-head.html
  packages/insomnia-components/package-lock.json
  packages/insomnia-components/package.json
Labels: UI/UX 🎨

#2467 Checking format to offset line number if spec string is JSON parsable.
  packages/insomnia-app/app/ui/components/spec-editor/spec-editor-sidebar.js
Labels: Bug

#2504 Updating readme for linux
  README.md
Labels: UI/UX 🎨

#2522 Fix insomnia-components version to 2.2.19 for kong portal plugin
  plugins/insomnia-plugin-kong-portal/.gitignore
  plugins/insomnia-plugin-kong-portal/.npmignore
  plugins/insomnia-plugin-kong-portal/dist/index.js
  plugins/insomnia-plugin-kong-portal/dist/index.js.map
  plugins/insomnia-plugin-kong-portal/package-lock.json
  plugins/insomnia-plugin-kong-portal/package.json
Labels: High Priority

#2527 Fixing hover icon positioning, overflow and core layout of header elements
  packages/insomnia-app/app/ui/components/wrapper-unit-test.js
  packages/insomnia-app/app/ui/css/components/editable.less
  packages/insomnia-app/app/ui/css/components/unit-tests.less
Labels: UI/UX 🎨

#2534 Unit tests buttons & select input styling
  packages/insomnia-app/app/ui/components/wrapper-unit-test.js
  packages/insomnia-app/app/ui/css/components/unit-tests.less
  packages/insomnia-app/app/ui/css/components/wrapper.less
Labels: UI/UX 🎨

#2533 Unit testing test output
  packages/insomnia-app/app/ui/components/wrapper-unit-test.js
  packages/insomnia-app/app/ui/css/components/unit-tests.less
  packages/insomnia-components/components/list-group/list-group-item.js
  packages/insomnia-components/components/list-group/list-group.js
  packages/insomnia-components/components/list-group/list-group.stories.js
  packages/insomnia-components/components/list-group/unit-test-result-badge.js
  packages/insomnia-components/components/list-group/unit-test-result-item.js
  packages/insomnia-components/components/list-group/unit-test-result-timestamp.js
  packages/insomnia-components/index.js
Labels: UI/UX 🎨
