Repository Kong/insomnia, pull requests merged in 2021-09, with the labels that each got.

#3977 [Feature/Plugin API] Add clipboard wrapper methods to context app
  packages/insomnia-app/app/__mocks__/electron.ts
  packages/insomnia-app/app/plugins/context/__tests__/app.test.ts
  packages/insomnia-app/app/plugins/context/app.tsx
Labels: A-plugin-api

#3983 fix(autocomplete) undefined tag values
  packages/insomnia-app/app/ui/components/codemirror/extensions/autocomplete.ts
Labels: B-bug

#3469 Handling vscode-languageserver with NMR
  packages/insomnia-app/webpack/webpack.config.base.ts
Labels: waiting-for-author

#2733 Add a keyboard shortcut for beautify request body
  packages/insomnia-app/app/common/hotkeys.ts
  packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
  packages/insomnia-app/app/ui/components/codemirror/modes/curl.ts
  packages/insomnia-app/app/ui/components/keydown-binder.ts
Labels: hacktoberfest-accepted

#2713 Improve visibilty of the drag pane when viewed vertically
  packages/insomnia-app/app/ui/components/settings/general.tsx
  packages/insomnia-app/app/ui/css/components/spec-editor.less
  packages/insomnia-app/app/ui/css/components/wrapper.less
Labels: hacktoberfest-accepted

#2725 Unescape xml links before opening it
  packages/insomnia-app/app/common/__tests__/misc.test.ts
  packages/insomnia-app/app/common/misc.ts
  packages/insomnia-app/app/ui/components/key-value-editor/row.tsx
  packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx
Labels: hacktoberfest-accepted

#2714 Show Client Certificate paths
  packages/insomnia-app/app/ui/components/modals/workspace-settings-modal.tsx
  packages/insomnia-app/app/ui/components/viewers/password-viewer.tsx
Labels: hacktoberfest-accepted

#2685 Added nested keys check after root keys check for environment editor.
  packages/insomnia-app/app/ui/components/editors/__tests__/environment-editor.test.ts
  packages/insomnia-app/app/ui/components/editors/environment-editor.tsx
Labels: hacktoberfest-accepted

#2726 Allow Autocomplete to be properly registered as a Shortcut
  packages/insomnia-app/app/codemirror.d.ts
  packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
  packages/insomnia-app/app/ui/components/codemirror/extensions/autocomplete.ts
  packages/insomnia-app/app/ui/components/codemirror/one-line-editor.tsx
  packages/insomnia-app/app/ui/components/editors/environment-editor.tsx
  packages/insomnia-app/app/ui/components/markdown-editor.tsx
  packages/insomnia-app/app/ui/components/modals/generate-code-modal.tsx
  packages/insomnia-app/app/ui/components/modals/settings-modal.tsx
  packages/insomnia-app/app/ui/components/settings/shortcuts.tsx
  packages/insomnia-app/app/ui/components/viewers/response-raw.tsx
  packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx
  packages/insomnia-app/app/ui/components/wrapper-design.tsx
  packages/insomnia-app/app/ui/components/wrapper.tsx
Labels: hacktoberfest-accepted

#3975 Plugin API feature: added getInfo method to context.app
  packages/insomnia-app/app/plugins/context/__tests__/app.test.ts
  packages/insomnia-app/app/plugins/context/app.tsx
Labels: A-plugin-api

#2715 Add export as HAR format for single requests
  packages/insomnia-app/app/common/__tests__/har.test.ts
  packages/insomnia-app/app/common/har.ts
  packages/insomnia-app/app/ui/components/dropdowns/preview-mode-dropdown.tsx
  packages/insomnia-app/app/ui/components/panes/response-pane.tsx
Labels: hacktoberfest-accepted
