Repository Kong/insomnia, pull requests merged in 2021-03, with the labels that each got.

#3132 Migration flow stylistic updates
  packages/insomnia-app/app/ui/components/onboarding-container.js
  packages/insomnia-app/app/ui/components/wrapper-migration.js
  packages/insomnia-app/app/ui/components/wrapper-onboarding.js
  packages/insomnia-app/app/ui/css/components/onboarding.less
  packages/insomnia-smoke-test/modules/migration.js
Labels: ui/ux

#3174 On create nav to new
  packages/insomnia-app/app/ui/components/wrapper-home.js
  packages/insomnia-smoke-test/core/app.test.js
Labels: ui/ux

#3198 Deploy to portal smoke test works again
  packages/insomnia-smoke-test/core/app.test.js
Labels: package/insomnia-smoke-test

#3208 Integrating loading state on Collection sync setup, refresh on local project setup
  packages/insomnia-app/app/ui/components/dropdowns/sync-dropdown.js
Labels: area/version-control, ui/ux

#3201 Updating cards to display accurate latest change timestamp
  packages/insomnia-app/app/ui/components/wrapper-home.js
Labels: ui/ux

#3231 Scroll support for unit testing
  packages/insomnia-app/app/ui/css/components/unit-tests.less
  packages/insomnia-app/app/ui/css/components/wrapper.less
Labels: A-ui-ux, B-regression

#3237 Upstream target host variable inclusion
  packages/openapi-2-kong/src/declarative-config/upstreams.js
Labels: B-bug, PA-openapi-2-kong
