Repository Kong/insomnia, pull requests merged in 2021-12, with the labels that each got.

#4307 removes onboarding activity and associated handling code
  packages/insomnia-app/app/common/__tests__/constants.test.ts
  packages/insomnia-app/app/common/constants.ts
  packages/insomnia-app/app/common/migrate-from-designer.ts
  packages/insomnia-app/app/main.development.ts
  packages/insomnia-app/app/models/settings.ts
  packages/insomnia-app/app/ui/components/settings/general.tsx
  packages/insomnia-app/app/ui/components/wrapper-onboarding.tsx
  packages/insomnia-app/app/ui/components/wrapper.tsx
  packages/insomnia-app/app/ui/redux/modules/__tests__/global.test.ts
  packages/insomnia-app/app/ui/redux/modules/global.tsx
  packages/insomnia-common/src/entities/settings.ts
  packages/insomnia-smoke-test/modules/onboarding.ts
Labels: T-tested-by-author, T-healthy

#4305 Chore: replace spectron with playwright
  .github/workflows/test.yml
  DEVELOPMENT.md
  packages/insomnia-app/app/main.development.ts
  packages/insomnia-smoke-test/.npmrc
  packages/insomnia-smoke-test/README.md
  packages/insomnia-smoke-test/core/app.test.ts
  packages/insomnia-smoke-test/core/import.test.ts
  packages/insomnia-smoke-test/core/migration.test.ts
  packages/insomnia-smoke-test/designer/app.test.ts
  packages/insomnia-smoke-test/fixtures/smoke-test-collection.yaml
  packages/insomnia-smoke-test/modules/application.ts
  packages/insomnia-smoke-test/modules/client.ts
  packages/insomnia-smoke-test/modules/component-names.ts
  packages/insomnia-smoke-test/modules/debug.ts
  packages/insomnia-smoke-test/modules/design.ts
  packages/insomnia-smoke-test/modules/dropdown.ts
  packages/insomnia-smoke-test/modules/find-async.ts
  packages/insomnia-smoke-test/modules/fixtures.ts
  packages/insomnia-smoke-test/modules/home.ts
  packages/insomnia-smoke-test/modules/migration.ts
  packages/insomnia-smoke-test/modules/modal.ts
  packages/insomnia-smoke-test/modules/onboarding.ts
  packages/insomnia-smoke-test/modules/settings.ts
  packages/insomnia-smoke-test/modules/tabs.ts
  packages/insomnia-smoke-test/modules/text.ts
  packages/insomnia-smoke-test/package-lock.json
  packages/insomnia-smoke-test/package.json
  packages/insomnia-smoke-test/playwright.config.ts
  packages/insomnia-smoke-test/playwright/paths.ts
  packages/insomnia-smoke-test/tests/app.test.ts
  packages/insomnia-smoke-test/tsconfig.build.json
  packages/insomnia-smoke-test/tsconfig.json
Labels: PA-smoke-test

#4319 Cleanup extra 'v' in version of the document card
  packages/insomnia-app/app/ui/components/__tests__/workspace-card.test.ts
  packages/insomnia-app/app/ui/components/workspace-card.tsx
Labels: T-tested-by-author, T-unhealthy
