Repository Kong/insomnia, pull requests merged in 2022-03, with the labels that each got.

#4519 Fix request switcher selection cycling
  packages/insomnia-app/app/ui/components/modals/__tests__/utils.test.tsx
  packages/insomnia-app/app/ui/components/modals/request-switcher-modal.tsx
  packages/insomnia-app/app/ui/components/modals/utils.ts
Labels: insomnia-stream

#4015 [Bug-fix] Ignoring circular references to prevent stack-overflow while importing an open-api specs
  packages/insomnia-importers/src/importers/openapi-3.ts
Labels: T-tested-by-author, T-healthy, insomnia-stream

#4602 chore(deps): updates xpath
  packages/insomnia-xpath/package-lock.json
  packages/insomnia-xpath/package.json
Labels: dependencies

#4600 chore(deps): update uuid
  packages/insomnia-app/app/common/analytics.ts
  packages/insomnia-app/app/common/database.ts
  packages/insomnia-app/app/common/misc.ts
  packages/insomnia-app/app/network/network.ts
  packages/insomnia-app/app/network/o-auth-2/misc.ts
  packages/insomnia-app/app/ui/components/cookie-list.tsx
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
  packages/insomnia-send-request/package-lock.json
  packages/insomnia-send-request/package.json
  packages/insomnia-smoke-test/package-lock.json
  packages/insomnia-smoke-test/package.json
  packages/insomnia-smoke-test/playwright/paths.ts
  plugins/insomnia-plugin-uuid/package-lock.json
  plugins/insomnia-plugin-uuid/package.json
Labels: dependencies

#4521 chore(deps): upgrade to react 17
  packages/insomnia-app/app/ui/components/error-boundary.tsx
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
  packages/insomnia-components/package-lock.json
  packages/insomnia-components/package.json
  plugins/insomnia-plugin-kong-portal/package-lock.json
  plugins/insomnia-plugin-kong-portal/package.json
Labels: dependencies

#4551 updates cross-env to latest (from prior: August 2016 version)
  package-lock.json
  package.json
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
  packages/insomnia-smoke-test/package-lock.json
  packages/insomnia-smoke-test/package.json
Labels: dependencies

#4582 chore(deps): mime-types update (and bug fix)
  packages/insomnia-app/app/network/multipart.ts
  packages/insomnia-app/app/ui/components/editors/body/body-editor.tsx
  packages/insomnia-app/app/ui/components/panes/response-pane.tsx
  packages/insomnia-app/app/ui/components/viewers/response-multipart-viewer.tsx
  packages/insomnia-app/app/ui/containers/app.tsx
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
  packages/insomnia-send-request/package-lock.json
  packages/insomnia-send-request/package.json
Labels: dependencies

#4610 chore(deps): removes @types/events
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
Labels: dependencies

#4614 chore(deps): removes whatwg-fetch (not needed since 5 years ago)
  packages/insomnia-app/app/__jest__/setup.ts
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
  packages/insomnia-send-request/package-lock.json
  packages/insomnia-send-request/package.json
Labels: dependencies

#4620 chore(deps): reselect
  packages/insomnia-app/app/models/api-spec.ts
  packages/insomnia-app/app/models/cookie-jar.ts
  packages/insomnia-app/app/models/environment.ts
  packages/insomnia-app/app/models/git-repository.ts
  packages/insomnia-app/app/models/o-auth-2-token.ts
  packages/insomnia-app/app/models/request-meta.ts
  packages/insomnia-app/app/models/response.ts
  packages/insomnia-app/app/models/stats.ts
  packages/insomnia-app/app/models/unit-test-result.ts
  packages/insomnia-app/app/models/unit-test-suite.ts
  packages/insomnia-app/app/models/workspace-meta.ts
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
  packages/insomnia-inso/src/db/models/types.ts
Labels: dependencies

#4615 chore(deps): updates redux-thunk
  packages/insomnia-app/app/ui/redux/modules/global.tsx
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
Labels: dependencies

#4618 chore(deps): multiparty
  packages/insomnia-app/package.json
  packages/insomnia-send-request/package.json
Labels: dependencies

#4611 chore(deps): replace moment.js with date-fns
  packages/insomnia-app/app/common/__tests__/misc.test.ts
  packages/insomnia-app/app/common/misc.ts
  packages/insomnia-app/app/ui/components/dropdowns/response-history-dropdown.tsx
  packages/insomnia-app/app/ui/components/editors/auth/components/auth-input-row.tsx
  packages/insomnia-app/app/ui/components/editors/auth/components/auth-private-key-row.tsx
  packages/insomnia-app/app/ui/components/editors/auth/components/auth-select-row.tsx
  packages/insomnia-app/app/ui/components/editors/auth/components/auth-toggle-row.tsx
  packages/insomnia-app/app/ui/components/editors/auth/o-auth-2-auth.tsx
  packages/insomnia-app/app/ui/components/modals/cookie-modify-modal.tsx
  packages/insomnia-app/app/ui/components/time-from-now.tsx
  packages/insomnia-app/app/ui/components/viewers/response-multipart-viewer.tsx
  packages/insomnia-app/app/ui/redux/modules/global.tsx
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
  plugins/insomnia-plugin-now/index.js
Labels: dependencies

#4636 All dependabot PRS 2022 03 24
  packages/insomnia-config/package-lock.json
  packages/insomnia-inso/package-lock.json
  packages/insomnia-send-request/package-lock.json
  packages/insomnia-smoke-test/package-lock.json
  packages/insomnia-testing/package-lock.json
  packages/openapi-2-kong/package-lock.json
Labels: dependencies

#4616 chore(deps): fuzzysort
  packages/insomnia-app/package-lock.json
  packages/insomnia-app/package.json
  packages/insomnia-components/package-lock.json
  packages/insomnia-components/package.json
  packages/insomnia-send-request/package-lock.json
  packages/insomnia-send-request/package.json
Labels: dependencies

#4607 Concating x-kong-security-openid-connect config with security schemas…
  packages/openapi-2-kong/src/declarative-config/security-plugins.test.ts
  packages/openapi-2-kong/src/declarative-config/security-plugins.ts
Labels: insomnia-stream
